language: go
go:
  - 1.7.x
  - 1.8.x

addons:
  apt:
    sources:
    - sourceline: 'ppa:masterminds/glide'
    packages:
    - glide

install:
  - mkdir $GOPATH/bin
  - ./bin/setup

script: ./bin/test
